import { Banner } from "src/types/Banners";

export const BannersStatic: Banner[] = [
    {
        id: 1,
        store_id: 2,
        title: { en: "Aspernatur sit aspe", ar: "edited-1 ar" },
        des: { en: "Odio reprehenderit", ar: "تحديث الوصف" },
        url: "http://updated-example.com",
        visibility: ["web"],
        created_at: "2024-06-15T19:43:31.000000Z",
        updated_at: "2024-06-24T09:20:37.000000Z",
        media: [
            {
                id: 223,
                model_type: "App\\Models\\Ad",
                model_id: 1,
                uuid: "92589d45-0098-4573-adfc-32375be43b37",
                collection_name: "images",
                name: "LoveKnot-Collection",
                file_name: "LoveKnot-Collection.webp",
                mime_type: "image/webp",
                disk: "public",
                conversions_disk: "public",
                size: 88858,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 2,
                created_at: "2024-06-24T09:18:40.000000Z",
                updated_at: "2024-06-24T09:18:40.000000Z",
                original_url: "http://localhost/storage/223/LoveKnot-Collection.webp",
                preview_url: ""
            }
        ]
    },
    {
        id: 2,
        store_id: 1,
        title: { en: "banner 1", ar: "banner ar" },
        des: { en: "description", ar: "description ar" },
        url: "https://banner-1.com",
        visibility: null,
        created_at: "2024-06-19T12:55:40.000000Z",
        updated_at: "2024-06-19T12:55:40.000000Z",
        media: []
    },
    {
        id: 3,
        store_id: 1,
        title: { en: "banner 1", ar: "banner ar" },
        des: { en: "description", ar: "description ar" },
        url: "https://banner-1.com",
        visibility: null,
        created_at: "2024-06-19T12:58:04.000000Z",
        updated_at: "2024-06-19T12:58:04.000000Z",
        media: [
            {
                id: 21,
                model_type: "App\\Models\\Ad",
                model_id: 3,
                uuid: "8b20ca2a-dc65-4c11-9915-d3fdfe8199be",
                collection_name: "images",
                name: "Half-Banner",
                file_name: "Half-Banner.webp",
                mime_type: "image/webp",
                disk: "public",
                conversions_disk: "public",
                size: 130338,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-19T12:58:04.000000Z",
                updated_at: "2024-06-19T12:58:04.000000Z",
                original_url: "http://localhost/storage/21/Half-Banner.webp",
                preview_url: ""
            }
        ]
    },
    {
        id: 4,
        store_id: 2,
        title: { en: "kdndknsk" },
        des: { en: "knknknkn" },
        url: "https://banner-4.org",
        visibility: null,
        created_at: "2024-06-19T14:05:21.000000Z",
        updated_at: "2024-06-19T14:05:21.000000Z",
        media: [
            {
                id: 22,
                model_type: "App\\Models\\Ad",
                model_id: 4,
                uuid: "d0eb4276-c8c4-4efc-bd92-03f5c789aaf4",
                collection_name: "images",
                name: "CBP9011072DI_Front",
                file_name: "CBP9011072DI_Front.webp",
                mime_type: "image/webp",
                disk: "public",
                conversions_disk: "public",
                size: 16356,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-19T14:05:21.000000Z",
                updated_at: "2024-06-19T14:05:21.000000Z",
                original_url: "http://localhost/storage/22/CBP9011072DI_Front.webp",
                preview_url: ""
            },
            {
                id: 23,
                model_type: "App\\Models\\Ad",
                model_id: 4,
                uuid: "1c37d09f-80ec-4ca5-8f76-2fc9f8d1085b",
                collection_name: "images",
                name: "BU901047OR_Back",
                file_name: "BU901047OR_Back.webp",
                mime_type: "image/webp",
                disk: "public",
                conversions_disk: "public",
                size: 27848,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 2,
                created_at: "2024-06-19T14:05:21.000000Z",
                updated_at: "2024-06-19T14:05:21.000000Z",
                original_url: "http://localhost/storage/23/BU901047OR_Back.webp",
                preview_url: ""
            }
        ]
    },
    {
        id: 5,
        store_id: 2,
        title: { en: "Asperiores reiciendi" },
        des: { en: "Error eligendi quae" },
        url: "https://banner555.org",
        visibility: null,
        created_at: "2024-06-19T15:51:03.000000Z",
        updated_at: "2024-06-19T15:51:03.000000Z",
        media: [
            {
                id: 29,
                model_type: "App\\Models\\Ad",
                model_id: 5,
                uuid: "d2363216-4a1f-4790-ba4d-093269adcb3f",
                collection_name: "images",
                name: "BU901047OR_Back",
                file_name: "BU901047OR_Back.webp",
                mime_type: "image/webp",
                disk: "public",
                conversions_disk: "public",
                size: 27848,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-19T15:51:03.000000Z",
                updated_at: "2024-06-19T15:51:03.000000Z",
                original_url: "http://localhost/storage/29/BU901047OR_Back.webp",
                preview_url: ""
            }
        ]
    },
    {
        id: 7,
        store_id: 1,
        title: { en: "banner 1", ar: "banner ar" },
        des: { en: "description", ar: "description ar" },
        url: "https://banner-1.com",
        visibility: ["web", "mobile"],
        created_at: "2024-06-23T06:23:35.000000Z",
        updated_at: "2024-06-23T06:23:35.000000Z",
        media: [
            {
                id: 153,
                model_type: "App\\Models\\Ad",
                model_id: 7,
                uuid: "6af7b462-e585-4373-91ba-1f5029897c35",
                collection_name: "images",
                name: "Half-Banner",
                file_name: "Half-Banner.webp",
                mime_type: "image/webp",
                disk: "public",
                conversions_disk: "public",
                size: 130338,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-23T06:23:35.000000Z",
                updated_at: "2024-06-23T06:23:35.000000Z",
                original_url: "http://localhost/storage/153/Half-Banner.webp",
                preview_url: ""
            }
        ]
    }
];