import { Category } from "src/types/Categories";

export const categoriesStatic: Category[] = [
    {
        id: 1,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-15T18:26:26.000000Z",
        updated_at: "2024-06-15T18:26:26.000000Z",
        products: [
            {
                id: 1,
                shop_brand_id: 257,
                name: "Quality-focused contextually-based encryption",
                slug: "quality-focused-contextually-based-encryption",
                sku: "59266150",
                barcode: "7219172104598",
                description: "The first question of course was, how to begin.' For, you see, as she said this, she noticed a curious plan!' exclaimed Alice. 'That's the reason of that?' 'In my youth,' Father William replied to.",
                qty: 8,
                security_stock: 7,
                featured: true,
                is_visible: true,
                old_price: 376.77,
                price: 391.19,
                cost: 82.7,
                type: "downloadable",
                backorder: false,
                requires_shipping: false,
                published_at: "2024-12-19T00:00:00.000000Z",
                seo_title: null,
                seo_description: null,
                weight_value: 0,
                weight_unit: "kg",
                height_value: 0,
                height_unit: "cm",
                width_value: 0,
                width_unit: "cm",
                depth_value: 0,
                depth_unit: "cm",
                volume_value: 0,
                volume_unit: "l",
                created_at: "2023-11-20T20:54:27.000000Z",
                updated_at: "2024-03-09T10:10:24.000000Z",
                media: [
                  {
                    id: 1,
                    model_type: "App\\Models\\Shop\\Product",
                    model_id: 1,
                    uuid: "b67b4f5d-77c7-462d-ba08-306ea0a80f5b",
                    collection_name: "product-images",
                    name: "680520bc-e880-4704-8dc7-a425d55b7a81",
                    file_name: "680520bc-e880-4704-8dc7-a425d55b7a81.jpg",
                    mime_type: "image/jpeg",
                    disk: "public",
                    conversions_disk: "public",
                    size: 4956,
                    manipulations: [],
                    custom_properties: [],
                    generated_conversions: [],
                    responsive_images: [],
                    order_column: 1,
                    created_at: "2024-06-27T12:53:14.000000Z",
                    updated_at: "2024-06-27T12:53:14.000000Z",
                    original_url: "https://7.onshophq.com/storage/1/680520bc-e880-4704-8dc7-a425d55b7a81.jpg",
                    preview_url: ""
                  }
                ]
              }
        ],
        media: [
            {
                id: 1,
                model_type: "App\\Models\\Category",
                model_id: 1,
                uuid: "42c1f3ae-a143-4d8a-ab32-dc62d01aec1e",
                collection_name: "images",
                name: "id",
                file_name: "id.png",
                mime_type: "image/png",
                disk: "public",
                conversions_disk: "public",
                size: 8750,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-15T18:26:26.000000Z",
                updated_at: "2024-06-15T18:26:26.000000Z",
                original_url: "http://localhost/storage/1/id.png",
                preview_url: ""
            }
        ]
    },
    {
        id: 2,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-15T19:08:06.000000Z",
        updated_at: "2024-06-15T19:34:39.000000Z",
        media: [
            {
                id: 2,
                model_type: "App\\Models\\Category",
                model_id: 2,
                uuid: "272f85d0-a704-4756-b049-c779566b421a",
                collection_name: "images",
                name: "screencapture-github-SaraKamalSaraya-OnShop-settings-access-2024-06-12-15_51_36",
                file_name: "screencapture-github-SaraKamalSaraya-OnShop-settings-access-2024-06-12-15_51_36.png",
                mime_type: "image/png",
                disk: "public",
                conversions_disk: "public",
                size: 315166,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-15T19:08:06.000000Z",
                updated_at: "2024-06-15T19:08:06.000000Z",
                original_url: "http://localhost/storage/2/screencapture-github-SaraKamalSaraya-OnShop-settings-access-2024-06-12-15_51_36.png",
                preview_url: ""
            }
        ]
    },
    {
        id: 3,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-19T14:23:00.000000Z",
        updated_at: "2024-06-19T14:23:00.000000Z",
        media: [
            {
                id: 24,
                model_type: "App\\Models\\Category",
                model_id: 3,
                uuid: "7b600dbd-9fbc-469a-ad2e-e90241a325a2",
                collection_name: "images",
                name: "Half-Banner_7acce5b5-1ccc-40b1-ace5-cd4b3906bac6",
                file_name: "Half-Banner_7acce5b5-1ccc-40b1-ace5-cd4b3906bac6.jpg",
                mime_type: "image/jpeg",
                disk: "public",
                conversions_disk: "public",
                size: 163739,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-19T14:23:00.000000Z",
                updated_at: "2024-06-19T14:23:00.000000Z",
                original_url: "http://localhost/storage/24/Half-Banner_7acce5b5-1ccc-40b1-ace5-cd4b3906bac6.jpg",
                preview_url: ""
            }
        ]
    },
    {
        id: 4,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-19T17:01:15.000000Z",
        updated_at: "2024-06-19T17:01:15.000000Z",
        media: [
            {
                id: 34,
                model_type: "App\\Models\\Category",
                model_id: 4,
                uuid: "a847c925-d6ea-486a-9726-810e3c99bba5",
                collection_name: "images",
                name: "IMG_6909",
                file_name: "IMG_6909.png",
                mime_type: "image/png",
                disk: "public",
                conversions_disk: "public",
                size: 444421,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-19T17:01:15.000000Z",
                updated_at: "2024-06-19T17:01:15.000000Z",
                original_url: "http://localhost/storage/34/IMG_6909.png",
                preview_url: ""
            }
        ]
    },
    {
        id: 5,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-20T07:44:07.000000Z",
        updated_at: "2024-06-20T07:44:07.000000Z",
        media: [
            {
                id: 37,
                model_type: "App\\Models\\Category",
                model_id: 5,
                uuid: "5660445a-d0fc-49de-be2a-34ec22a68c85",
                collection_name: "images",
                name: "IMG_6923",
                file_name: "IMG_6923.png",
                mime_type: "image/png",
                disk: "public",
                conversions_disk: "public",
                size: 1418590,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-20T07:44:07.000000Z",
                updated_at: "2024-06-20T07:44:07.000000Z",
                original_url: "http://localhost/storage/37/IMG_6923.png",
                preview_url: ""
            }
        ]
    },
    {
        id: 6,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-20T10:13:22.000000Z",
        updated_at: "2024-06-20T10:13:22.000000Z",
        media: [
            {
                id: 41,
                model_type: "App\\Models\\Category",
                model_id: 6,
                uuid: "a6e54603-210a-4261-bcbd-7e4d4d1ee8d9",
                collection_name: "images",
                name: "Screenshot_1",
                file_name: "Screenshot_1.png",
                mime_type: "image/png",
                disk: "public",
                conversions_disk: "public",
                size: 402342,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-20T10:13:22.000000Z",
                updated_at: "2024-06-20T10:13:22.000000Z",
                original_url: "http://localhost/storage/41/Screenshot_1.png",
                preview_url: ""
            }
        ]
    },
    {
        id: 7,
        parent_id: null,
        name: "aa",
        slug: "",
        description: "aa",
        position: 1,
        is_visible: true,
        seo_title: "seo title",
        seo_description: "seo_description",
        pivot: {
            shop_product_id: 1,
            shop_category_id: 1,
            created_at: "",
            updated_at: "",
        },
        created_at: "2024-06-20T10:13:22.000000Z",
        updated_at: "2024-06-20T10:13:22.000000Z",
        media: [
            {
                id: 41,
                model_type: "App\\Models\\Category",
                model_id: 6,
                uuid: "a6e54603-210a-4261-bcbd-7e4d4d1ee8d9",
                collection_name: "images",
                name: "Screenshot_1",
                file_name: "Screenshot_1.png",
                mime_type: "image/png",
                disk: "public",
                conversions_disk: "public",
                size: 402342,
                manipulations: [],
                custom_properties: [],
                generated_conversions: [],
                responsive_images: [],
                order_column: 1,
                created_at: "2024-06-20T10:13:22.000000Z",
                updated_at: "2024-06-20T10:13:22.000000Z",
                original_url: "http://localhost/storage/41/Screenshot_1.png",
                preview_url: ""
            }
        ]
    },
    
];
